### ISSUE TITLE
User perspective: intégrer la fonction dictionary dans la fonction encrypt

### ISSUE THREAD

**Issue by lnalborczyk** [cedricbatailler/maskr#13]
Faciliter l'utilisation du package en intégrant `dictionary` dans `encrypt` et `decrypt`, de sorte à ce que l'utilisateur n'ait qu'à renseigner la dataframe, et la variable à encrypter.

**Comment by cedricbatailler** [comment]
Et on stockerait le dictionnaire où ? Dans le data.frame directement ?

**Comment by lnalborczyk** [comment]
See #14
