### ISSUE TITLE
Crypter (et décrypter) plusieurs variables en même temps

### ISSUE THREAD

**Issue by cedricbatailler** [cedricbatailler/maskr#3]
Réfléchir à comment implémenter ça, pour l'instant je pense que `tidyr` et `purrr` pourraient être utiles.

**Comment by cedricbatailler** [comment]
Définitivement faisable avec `lazyeval::lazy_dots()`. Permettrait à l'utilisateur de spécifier plusieurs variables sans pour autant avoir à envoyer un vecteur.

A noté que du coup il faudra vérifier que le premier argument des fonctions utilisant le dictionnaire soit bien le dictionnaire.

**Comment by cedricbatailler** [comment]
Pour l'instant je peux implémenter ça sous forme de boucles qui tourne à chaque fonction mais il faudra voir si il y a moyen de parallélisé ça.

**Comment by lnalborczyk** [comment]
J'essaye de m'occuper de ça ce week-end !

**Comment by cedricbatailler** [comment]
techniquement il faudrait tout réécrire en ce qui concerne l'évaluation. Les nouveaux standards sont à rearder du côté de `rlang`. Je pense que ça facilitera l'écriture du code d'utiliser ça.

**Comment by cedricbatailler** [comment]
voir http://dplyr.tidyverse.org/articles/programming.html
