### ISSUE TITLE
Ajout d'exemple dans la doc + README

### ISSUE THREAD

**Issue by cedricbatailler** [cedricbatailler/maskr#7]
Possibilité d'utiliser un jeu de données de base du genre `mtcars` pour le faire.
Egalement, pour faciliter les exemples, penser à utiliser `reprex`, ça devrait être plus facile.

**Comment by lnalborczyk** [comment]
Je préfère `ChickenWeights`mais je peux faire un effort et utiliser `mtcars`. Je ne connais pas `reprex`mais ça a l'air fun (jusque là j'ai simplement fait des exemples avec roxygen2)...

**Comment by cedricbatailler** [comment]
ça me va pour `ChickWeight` ! pour ce qui est de `reprex`, ça permet juste de pouvoir écrire des trucs qui sont directement copier/collable avec l'input et l'output
