### ISSUE TITLE
Vérifier que les variables numériques soient utilisable après encrypt/decrypt

### ISSUE THREAD

**Issue by cedricbatailler** [cedricbatailler/maskr#9]
J'y avais pas pensé plus tôt mais il y a moyen que la nature de la variable soit plus la même après avoir été cryptée.

**Comment by lnalborczyk** [comment]
Visiblement non. En tout cas pas dans la dernière version que j'ai commit. J'ai testé avec des variables de classe `numeric`, `integer`, `character`,  ou `factor`, et les classes sont bien conservées. Je ferme donc.
